### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by SabujGolui** [SabujGolui/SQL-Notes#4]

**Comment by pixobia** [comment]
i can update readme file by writing how to contribute,to this repo,and if you provied some other information i can add it ,if you are ok ,Assign this to me..

**Comment by SabujGolui** [comment]
Ok go Ahead

**Comment by pixobia** [comment]
would like to elborate what is SQL notes mainly...

**Comment by SabujGolui** [comment]
The SQL part is taken care of by @issue31

**Comment by pixobia** [comment]
done once review it please...

**Comment by SabujGolui** [comment]
you can add some codes as well

**Comment by pixobia** [comment]
create another issue and provide me the code ,to be fact i doesnt know more about sql if you can provide i can add it as well
